version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
      - JWT_SECRET=apply_digital_javascript_back_end_developer_test
      - CONTENTFUL_SPACE_ID=9xs1613l9f7v
      - CONTENTFUL_ACCESS_TOKEN=I-ThsT55eE_B3sCUWEQyDT4VqVO3x__20ufuie9usns
      - CONTENTFUL_ENVIRONMENT=master
      - CONTENTFUL_CONTENT_TYPE=product
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
